import type { Metadata } from "next";
import {Inter, Calistoga} from 'next/font/google';
import {twMerge} from 'tailwind-merge'
import "./globals.css";
import  ActiveSectionContextProvider  from "@/context/ActiveSectionContext";
import Header from "@/sections/Header";

const inter = Inter({
  variable: "--font-sans",
  subsets: ['latin']
});
const calistoga = Calistoga({
  variable: "--font-serif",
  subsets: ['latin'],
  weight:['400']
});

export const metadata: Metadata = {
  title: "My-Portfolio ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className=
        {twMerge(
          inter.variable, 
          calistoga.variable,
          "bg-gray-900 text-white antialiased font-sans" )}
      >
        <ActiveSectionContextProvider>
          <Header />
          {children}
        </ActiveSectionContextProvider>
        
      </body>
    </html>
  );
}
